# Modul Numpy

Numpy biasanya digunakan dalam perhitungan operasi matematik.
Dengan menggunakan numpy perhitungan akan menjadi lebih mudah untuk dituliskan.

In [8]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print(x)

[[347568904       455]
 [347568968       455]
 [347569032       455]]


In [11]:
x[0][1]=100
x

array([[347568904,       100],
       [347568968,       455],
       [347569032,       455]])

In [13]:
x = np.zeros(5) 
print(x)

[0. 0. 0. 0. 0.]


In [15]:
x = np.ones(5) 
print(x)

[1. 1. 1. 1. 1.]


In [18]:
x = np.ones([2,2], dtype = int) 
print(x)

[[1 1]
 [1 1]]


In [20]:
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [22]:
x = np.arange(10,20,2) 
print(x)

[10 12 14 16 18]


In [23]:
x = np.linspace(10,20,5) 
print(x)

[10.  12.5 15.  17.5 20. ]


In [25]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  

# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [27]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:')
print(a) 
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:')
print(a[...,1])
print('\n')  

# Now we will slice all items from the second row 
print('The items in the second row are:')
print(a[1,...]) 
print('\n')  

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:')
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
[3 4 5]


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [31]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [33]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.vdot(a,b)

130

In [34]:
print(np.inner(np.array([1,2,3]),np.array([0,1,0])))

2


In [36]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print(b)
print(np.linalg.det(b))
print(6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


In [38]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print(x)
print(y) 
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
